version: '3.8'

services:
  n8n:
    build:
      context: . # Build from the current directory where the Dockerfile is located
      dockerfile: Dockerfile
    container_name: n8n
    restart: always
    ports:
      - "5678:5678" # Host_Port:Container_Port
    volumes:
      - n8n_data:/home/node/.n8n # Linux/Mac path
      # For Windows, you might need to adjust the host path or use Docker Desktop's default volume management.
      # Example for Windows (if you want to map to a specific host folder):
      # - C:\path\to\your\n8n_data:/home/node/.n8n
    environment:
      # Optional: Configure n8n for production, database, etc.
      # For SQLite (default), no extra DB config is needed here.
      # - N8N_HOST=localhost
      # - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE = false
      - WEBHOOK_URL=http://localhost:5678/ # Replace with your actual public URL if needed
      # - N8N_USER_MANAGEMENT_ENABLED=true # Enable user management
      # - N8N_EMAIL_MODE=smtp # Example for email
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=n8nuser
      # - N8N_BASIC_AUTH_PASSWORD=n8npassword
volumes:
  n8n_data: # Define a named volume
  # fixed the cookie issue
